# Generated by Django 4.1.7 on 2023-03-25 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='menu name')),
                ('slug', models.SlugField(max_length=100, verbose_name='menu name for url')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='menu item name')),
                ('slug', models.SlugField(max_length=100, verbose_name='menu item name for url')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treelikemenu.menu', verbose_name='menu name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treelikemenu.menuitem', verbose_name='submenu')),
            ],
            options={
                'verbose_name': 'MenuItem',
                'verbose_name_plural': 'MenuItems',
                'ordering': ['pk'],
            },
        ),
    ]
